### ISSUE TITLE
synchronize config only if it has changed

### ISSUE THREAD

**Issue by OfCores** [IsiTapier/AIRduino#44]
Wie könnte man da aber eine Rückkopplung verhindern?

**Comment by IsiTapier** [comment]
Der Ardu weiß ja wenn er was von der Datenbank empfängt und dafür gibts ja dann den setValue(value, false) Befehl, der das dann nicht wieder hochläd

**Comment by IsiTapier** [comment]
Und am besten nur die Spalten die sich geändert haben, um unnötige Datenübertragung zu vermeiden
